// Generate INDEX.md — catalog grouped by primary domain.

import { join } from "node:path";
import type { Skill } from "../types.ts";

const UNCLASSIFIED = "_unclassified";

function oneLine(desc: string): string {
  const flat = desc.replace(/\s+/g, " ").trim();
  if (flat.length <= 160) return flat;
  return flat.slice(0, 157).trimEnd() + "...";
}

/**
 * Build the INDEX.md content string from a loaded library. Groups by
 * primaryDomain, retired skills listed in a trailing section.
 */
export function generateIndex(
  skills: Skill[],
  opts: { generatedAt?: string } = {},
): string {
  const active = skills.filter((s) => !s.retired);
  const retired = skills.filter((s) => s.retired);

  const byDomain = new Map<string, Skill[]>();
  for (const s of active) {
    const d = s.primaryDomain ?? UNCLASSIFIED;
    const arr = byDomain.get(d);
    if (arr) arr.push(s);
    else byDomain.set(d, [s]);
  }

  const domains = [...byDomain.keys()].sort((a, b) => {
    if (a === UNCLASSIFIED) return 1;
    if (b === UNCLASSIFIED) return -1;
    return a < b ? -1 : 1;
  });

  const lines: string[] = [];
  lines.push("# Skill Index");
  lines.push("");
  lines.push(
    `> Generated by \`skl index\`. ${active.length} active skill${active.length === 1 ? "" : "s"}` +
      (retired.length ? `, ${retired.length} retired` : "") +
      ` across ${domains.length} domain${domains.length === 1 ? "" : "s"}.`,
  );
  const ts = opts.generatedAt ?? new Date().toISOString();
  lines.push(`> Last generated: ${ts}`);
  lines.push("");

  for (const domain of domains) {
    const arr = byDomain
      .get(domain)!
      .slice()
      .sort((a, b) => (a.name < b.name ? -1 : 1));
    lines.push(`## ${domain}`);
    lines.push("");
    for (const s of arr) {
      const extra = s.domains.filter((d) => d !== s.primaryDomain);
      const tags = extra.length ? ` _(also: ${extra.join(", ")})_` : "";
      const prov = s.source ? ` \`[${s.source.source}]\`` : "";
      lines.push(`- **${s.name}**${tags}${prov} — ${oneLine(s.description)}`);
    }
    lines.push("");
  }

  if (retired.length) {
    lines.push("## _retired");
    lines.push("");
    for (const s of retired.slice().sort((a, b) => (a.name < b.name ? -1 : 1))) {
      lines.push(`- ~~${s.name}~~ — ${oneLine(s.description)}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/** Write INDEX.md into the library root. Returns the path written. */
export async function writeIndex(
  libraryPath: string,
  skills: Skill[],
  opts: { generatedAt?: string } = {},
): Promise<string> {
  const content = generateIndex(skills, opts);
  const out = join(libraryPath, "INDEX.md");
  await Bun.write(out, content + "\n");
  return out;
}
